# Generated by Django 2.2.2 on 2019-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='url',
            field=models.URLField(),
        ),
    ]
